<a href="https://colab.research.google.com/github/BData97/core-python/blob/main/02_Numpy_Exercise_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
ten_zeros=np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
ten_ones=np.ones(10)
ten_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
ten_fives=np.ones(10)*5
ten_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [12]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [63]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [64]:
mat=np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [66]:
mat=np.zeros([3,3])
mat[1,1]=1
mat[0,0]=1
mat[2,2]=1
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [52]:
from numpy import random
ra=random.rand()
ra

0.00662518735910389

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [61]:
x=np.random.normal(0,1,25)
x

array([ 0.12361969, -1.19511773,  1.49018282, -0.84793892,  0.54585723,
       -0.01470157,  0.21629813, -0.43785111, -1.36225451, -1.54253641,
       -0.15406062,  0.63923634, -1.64498765, -0.72434324, -1.14084111,
        0.67649029, -0.09736237,  0.41605211, -0.62510857,  0.94499369,
       -0.2026171 , -1.25896165, -1.54840949, -0.3815627 ,  0.41623263])

In [76]:
x=np.random.randn(25)
x

array([ 0.36768262,  0.6905832 ,  0.75141789,  0.67771591,  0.40931529,
       -0.89451028, -0.62398726,  1.55741563,  0.6505006 ,  0.08969324,
        0.85518786, -0.11459406, -0.48492324,  1.46246645,  0.82947377,
        0.04472186, -0.67269395, -1.14877719,  1.04739051, -1.14315904,
       -0.20569231,  0.09044739, -0.19154826,  0.38083285, -1.17367755])

array([0.55133721, 0.89385201, 0.75559429, 0.49801604, 0.24855126,
       0.13258941, 0.45452877, 0.75183726, 0.1750282 , 0.22104586,
       0.18050344, 0.94066898, 0.71121223, 0.76065241, 0.84688756,
       0.66625014, 0.99816277, 0.15130846, 0.32376193, 0.43479406,
       0.29856445, 0.86790664, 0.19391454, 0.15762885, 0.53837182])

#### Create the following matrix:

In [83]:
x=np.arange(1,101).reshape(10,10)/100
x

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [90]:
a=np.linspace(0,1,20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.00052632, 0.00105263, 0.00157895, 0.00210526,
       0.00263158, 0.00315789, 0.00368421, 0.00421053, 0.00473684,
       0.00526316, 0.00578947, 0.00631579, 0.00684211, 0.00736842,
       0.00789474, 0.00842105, 0.00894737, 0.00947368, 0.01      ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [95]:
arr=np.arange(1,26)
arr=arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [30]:
arr[0:3,0:3]


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
arr[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [38]:
arr.sum()

325

#### Get the standard deviation of the values in mat

In [40]:
arr.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!